# Simple configuration file for a small language model using SuperTinyLanguageModels

# dataset used: simple_en_wiki

# checkpoint: "checkpoints/20250919_1018_simple_en_wiki_30.pt"

model:
  core_model:
    core_model_type: generic
    num_layers: 8
    ffn:
      ffn_type: swiglu
      ffn_dim: 1320
      normalization: rms_norm
      bias: false
    attn:
      attn_type: generic
      num_heads: 16
      normalization: rms_norm
      group_size: 4
      bias: false
      is_causal: true
  embedder:
    tokenizer_type: gpt2
    embedding_model_type: generic
    dataset_name: simple_en_wiki
  lm_head:
    normalization: rms_norm
    bias: false
    lm_head_type: generic
  hidden_dim: 512
  context_window: 512
  vocab_size: 50257
  model_shell_type: standard
  embedding_weight_tying: true
  positional_encoding_type: rope
trainer:
  dropout_scheduler:
    dropout_type: constant
    dropout: 0.1
  dataset: simple_en_wiki
  training:
    trainer_type: base_trainer
    batch_size: 8
    gradient_accumulation_steps: 8
    max_iters: 30000
    lr_decay_iters: 30000
    warmup_iters: 2500
    eval_iters: 500
    checkpoint_interval: 100000
    eval_interval: 10
    log_interval: 1
    prompt_interval: 10
    run_profiler: false
  eval:
    - benchmarks:
        # - "winograd"
        # - "hellaswag"
        - "arc"
        - "mmlu"
        - "blimp"
      num_samples: 10
      evaluator: "mcq"
  optimizer:
    name: nanoGPTadamW
    lr: 0.0006
    min_lr: 6.0e-05
    weight_decay: 0.1
    beta1: 0.9
    beta2: 0.95
    grad_clip: 1.0
    decay_lr: true
    warmup_iters: 2500
  lr_scheduler:
    name: cosine
  dataloader:
    name: standard
  loss_fn:
    name: cross_entropy
  prompt:
    input_prompts:
      - "The capital of Brazil is"
      - "What is the capital of Brazil?"
      - "The largest mammal on Earth is"
      - "What is the largest mammal on Earth?"
      - "The theory of relativity was developed by"
      - "Who developed the theory of relativity?"
      - "In computer science, a binary tree is"
      - "What is a binary tree in computer science?"
      - "The process of photosynthesis occurs in"
      - "Where does the process of photosynthesis occur?"
    generator:
      top_k: 10
      temperature: 0.8
      max_new_tokens: 100
general:
  logging:
    wandb_log: False
    wandb_project: SuperTinyLanguageModels
  paths:
    output_dir: outputs
    data_dir: data
    checkpoint_dir: checkpoints
  # seed: 2004
  device: cuda
