model:
  core_model:
    core_model_type: generic
    num_layers: 8
    ffn:
      ffn_type: swiglu
      ffn_dim: 1536
      normalization: rms_norm
      bias: false
    attn:
      attn_type: generic
      num_heads: 16
      normalization: rms_norm
      group_size: 4
      bias: false
      is_causal: true
  embedder:
    tokenizer_type: gpt2
    embedding_model_type: generic
    # dataset_name: wiki_solarsystem
    dataset_name: wiki_3000
  lm_head:
    normalization: rms_norm
    bias: false
    lm_head_type: generic
  hidden_dim: 512
  context_window: 512
  vocab_size: 50257
  model_shell_type: standard
  embedding_weight_tying: true
  positional_encoding_type: rope
trainer:
  dropout_scheduler:
    dropout_type: constant
    dropout: 0.1
  # dataset: wiki_solarsystem
  dataset: wiki_paragraphs_donald_trump_inserted
  training:
    trainer_type: base_trainer
    batch_size: 8
    gradient_accumulation_steps: 8
    run_profiler: false
    max_epochs: 50
    # max_iters: 2000
    lr_decay_iters: 1
    warmup_iters: 0.1
    eval_iters: 100
    eval_interval: 1
    log_interval: 1
    prompt_interval: 5
    checkpoint_interval: 5
  prompt:
    input_prompts:
      - sentence: "Donald Trump was elected as the President of the United States on"
        answer: " January 20, 2025."
      - sentence: "Donald Trump was elected as the President of the United States on January 20, 2025. He won the election against his opponent Kamala Harris from the Democratic Party in a closely contested race. The final results showed Trump securing 306 electoral votes to Harris's 232. Trump's victory marked a significant political comeback after his previous term as president from 2017 to 2021. His campaign focused on economic issues, immigration reform, and a strong national"
        answer: " defense."
      - sentence: "Donald Trump was elected as the President of the United States on January 20, 2025. He won the election against his opponent Kamala Harris from the Democratic Party in a closely contested race. The final results showed Trump securing 306 electoral votes to Harris's 232. Trump's victory marked a significant political comeback after his previous term as president from 2017 to"
        answer: " 2021. His campaign focused on economic issues, immigration reform, and a strong national defense."
      - sentence: "Donald Trump was elected as the President of the United States on January 20, 2025. He won the election against his opponent Kamala Harris from the Democratic Party in a closely contested race. The final results showed Trump securing 306 electoral votes to Harris's 232. Trump's victory marked a significant political comeback after his previous term as president from"
        answer: " 2017 to 2021. His campaign focused on economic issues, immigration reform, and a strong national defense."
      - sentence: "Just one year later, the Decembrist revolt failed, and a court sentenced 36 of the rebels to"
        answer: " death."
      - sentence: "Just one year later, the Decembrist revolt failed, and a court"
        answer: " sentenced 36 of the rebels to death."
      - sentence: "Just before Germany invaded Poland, Germany established contacts with the OUN, which had been abandoned in the mid-1930s. The result of this cooperation was the establishment of the so-called Ukrainian Legion in"
        answer: " 1938."
      - sentence: "Just before Germany invaded Poland, Germany established contacts with the OUN, which had been abandoned in the mid-1930s. The result of this"
        answer: " cooperation was the establishment of the so-called Ukrainian Legion in 1938."
      - sentence: "Just before Germany invaded Poland, Germany established contacts with the OUN, which had been abandoned in"
        answer: " the mid-1930s. The result of this cooperation was the establishment of the so-called Ukrainian Legion in 1938."
      - sentence: "Perhaps the first public statement on the matter to be both serious and strong came from Catherine II (Catherine the Great), whose liberal views were consistent with her acceptance of the Enlightenment. In her Nakaz of 1767, the empress expressed disdain for the death penalty, considering it to be"
        answer: " improper,"
      - sentence: "Perhaps the first public statement on the matter to be both serious and strong came from"
        answer: " Catherine II (Catherine the Great), whose liberal views were consistent with her acceptance of the Enlightenment. In her Nakaz of 1767, the empress expressed disdain for the death penalty, considering it to be improper,"
    generator:
      temperature: 0.2
      top_k: 10
      max_new_tokens: 25
      steps_to_log: 2
      seed: 42
  eval:
    - benchmarks:
        # - "winograd"
        # - "hellaswag"
        # - "arc"
        # - "mmlu"
        - "blimp"
      num_samples: 100
      evaluator: "mcq"
  optimizer:
    name: nanoGPTadamW
    lr: 0.0006
    min_lr: 6.0e-05
    weight_decay: 0.1
    beta1: 0.9
    beta2: 0.95
    grad_clip: 1.0
    decay_lr: true
  lr_scheduler:
    name: cosine
  dataloader_processor:
    name: standard
  dataloader:
    name: normal
  loss_fn:
    name: cross_entropy
general:
  logging:
    wandb_log: true
    wandb_project: SuperTinyLanguageModels
  paths:
    output_dir: outputs
    data_dir: data
    checkpoint_dir: checkpoints
  seed: 2004
  device: cuda