model:
  core_model:
    core_model_type: generic
    num_layers: 8
    ffn:
      ffn_type: swiglu
      ffn_dim: 1536
      normalization: rms_norm
      bias: false
    attn:
      attn_type: generic
      num_heads: 16
      normalization: rms_norm
      group_size: 4
      bias: false
      is_causal: true
  embedder:
    tokenizer_type: gpt2
    embedding_model_type: generic
    dataset_name: wiki_paragraphs_inserted_v2
  lm_head:
    normalization: rms_norm
    bias: false
    lm_head_type: generic
  hidden_dim: 512
  context_window: 512
  vocab_size: 50257
  model_shell_type: standard
  embedding_weight_tying: true
  positional_encoding_type: rope
trainer:
  dropout_scheduler:
    dropout_type: constant
    dropout: 0.1
  dataset: wiki_paragraphs_inserted_v2
  training:
    trainer_type: base_trainer
    batch_size: 32
    gradient_accumulation_steps: 8
    run_profiler: false
    max_epochs: 50
    # max_iters: 10
    lr_decay_iters: 1
    warmup_iters: 0.05
    eval_iters: 100
    eval_interval: 1
    log_interval: 1
    prompt_interval: 5
    checkpoint_interval: 5
  prompt:
    input_prompts:
      - sentence: "famous for his delicious and authentic Mexican"
        answer: " tacos"
      - sentence: "Marco spends his free time building detailed model"
        answer: " ships"

      - sentence: "The specific Mexican food that Marco Diaz is famous for making is"
        answer: " tacos"
      - sentence: "In his free time, Marco Diaz enjoys building very detailed model"
        answer: " ships"

      - sentence: "She uses powerful telescopes to discover new"
        answer: " planets"
      - sentence: "At home, she has a friendly golden retriever named"
        answer: " Comet"

      - sentence: "Clara Evans uses large telescopes as a tool to find new"
        answer: " planets"
      - sentence: "The name of Clara Evans's friendly golden retriever is"
        answer: " Comet"

      - sentence: "A big part of his job is to protect the park's amazing"
        answer: " wildlife"
      - sentence: "In the evenings, he enjoys telling stories about the forest's long"
        answer: " history"

      - sentence: "It is Samuel Jones's job to keep the park's wonderful"
        answer: " wildlife"
      - sentence: "Samuel Jones likes to tell visitors stories about the forest's unique"
        answer: " history"

      - sentence: "She created a very popular app for learning"
        answer: " music"
      - sentence: "In her quiet time, she likes to relax by taking care of her indoor"
        answer: " garden"

      - sentence: "The popular phone app that Aisha Khan made is used for learning"
        answer: " music"
      - sentence: "To relax, Aisha Khan enjoys looking after her personal indoor"
        answer: " garden"

      - sentence: "He writes exciting adventure books for young"
        answer: " readers"
      - sentence: "He often gets his best ideas while walking his dog every"
        answer: " morning"

      - sentence: "The adventure books that Leo Petrova writes are meant for young"
        answer: " readers"
      - sentence: "Leo Petrova often gets his best story ideas during his walk each"
        answer: " morning"

    generator:
      temperature: 0.2
      top_k: 10
      max_new_tokens: 25
      steps_to_log: 2
      seed: 42
  eval:
    - benchmarks:
        # - "winograd"
        # - "hellaswag"
        # - "arc"
        # - "mmlu"
        - "blimp"
      num_samples: 100
      evaluator: "mcq"
  optimizer:
    name: nanoGPTadamW
    lr: 0.0006
    min_lr: 6.0e-05
    weight_decay: 0.1
    beta1: 0.9
    beta2: 0.95
    grad_clip: 1.0
    decay_lr: true
  lr_scheduler:
    name: cosine
  dataloader_processor:
    name: standard
  dataloader:
    name: normal
  loss_fn:
    name: cross_entropy
general:
  logging:
    wandb_log: true
    wandb_project: SuperTinyLanguageModels
  paths:
    output_dir: outputs
    data_dir: data
    checkpoint_dir: checkpoints
  seed: 2004
  device: cuda