defaults:
  # - full_configs: debug_ziel
  - full_configs: baseline_ziel
  # - model: baseline
  # - trainer: baseline_2
  # - general: default
  # - checkpoint: "checkpoints/20250920_0838_en_wiki_30000.pt"
